let game = new Game();
game.addPlayer("Peter");
game.addPlayer("Brigitte");
game.addPlayer("Linda");
game.addPlayer("Alina");
game.runGame();
// let graphic = new Graphic();
// graphic.drawPlayer(0);
// graphic.drawPlayer(1);
// graphic.drawPlayer(2);
// graphic.drawPlayer(3);
// game.setupGame();
// game.doTresor("red");
// game.doTresor("pink");
// game.doTresor("red");
// game.doTresor("red");
// game.doTresor("red");
// game.doTresor("blue");
// game.doTresor("blue");
// game.doTresor("blue");
// game.doTresor("green");
// game.doTresor("blue");
